### ISSUE TITLE
fix formatting on worldwide PDM 

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/Localized-Public-Domain-Mark#4]
Formatting is off starting with moral rights statement on the mark:  http://creativecommons.org/publicdomain/mark/1.0/

**Comment by mattl** [comment]
On this. Yahoo's SSL cert expired.

**Comment by mattl** [comment]
http://creativecommons.org/publicdomain/mark/1.0/

**Comment by mattl** [comment]
I believe this is fixed now

**Comment by peterspdx** [comment]
Indeed it is.  Thanks!
